Insert into Tienda (tie_tipo, fklugar) values
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='El Cafetal' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Maracaibo' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Iribarren' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Simón Rodríguez' and lug_tipo='Municipio' and fklugar=1602)),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Guanare' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Falcón' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Valle de la Pascua' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Pedro María Ureña' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='San Félix' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Torres' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Páez' and lug_tipo='Municipio' and fklugar=1617)),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Cárdenas' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Petare' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Atanasio Girardot' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Caroní' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='San Cristóbal' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Los Teques' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Anaco' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='San Casimiro' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='San Antonio de los Altos' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Antímano' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='La Guaira' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Nueva Esparta' and lug_tipo='Estado')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Guanta' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Puerto La Cruz' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Mérida' and lug_tipo='Estado')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Barinas' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Tucacas' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Zulia' and lug_tipo='Estado')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='La Victoria' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Zamora' and lug_tipo='Municipio' and fklugar=1604)),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Lagunillas' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Heres' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Simón Bolívar' and lug_tipo='Municipio' and fklugar=1602)),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='San Fernando' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Valencia' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Maiquetía' and lug_tipo='Parroquia')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Bermúdez' and lug_tipo='Municipio')),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Miranda' and lug_tipo='Municipio' and fklugar=1610)),
('MiniCandyUCAB', (Select lug_id from public.lugar where lug_nombre='Trujillo' and lug_tipo='Municipio'));
