Insert into Producto (pro_nombre,pro_relleno,pro_textura,pro_puntuacion,pro_ruta_imagen,pro_descripcion,fksabor, fktipo,pro_precio) values 
('Chupetas rimbombin', 'Chicle, chocolate', 'Suave', 5, '/images/6.jpg','Chupetas en forma de margaritas con rellno de chicle, chocolate y pueden adquirirse sin azucar.',
(SELECT sab_id FROM sabor where sab_nombre='Fresa'), (SELECT tip_id FROM tipo where tip_nombre='Piruleta'), 2000),
('Ricolin', NULL,'Rigida', 7, '/images/2.jpg','Caramelos supresores de la tos, sus sabores mas famosos son citricos y mentolados (poseen vitamina C).', 
(SELECT sab_id FROM sabor where sab_nombre='Citrico'), (SELECT tip_id FROM tipo where tip_nombre='Macizo'), 4530),
('Firi Firi', NULL, 'Rigida', 4 , '/images/3.jpg','Pastillas que proporcionan frescura, vienen en muchos sabores pero el mas particular es el de menta (todos vienen sin azucar).',
(SELECT sab_id FROM sabor where sab_nombre='Menta'), (SELECT tip_id FROM tipo where tip_nombre='Gelatina'), 2103),
('Chupetas Corazon', NULL,'Rigida', 2 , '/images/corazon.jpg','Es la perfecta combinacion entre el suave sabor de la fresa con un polvo picante.',
(SELECT sab_id FROM sabor where sab_nombre='Fresa'), (SELECT tip_id FROM tipo where tip_nombre='Piruleta'), 1321),
('Los pirulitos', NULL,'Blandos', 8, '/images/pirulitos.jpg', 'Caramelos blandos con forma alargada, esta presentacion viene en un total de 6 sabores.',
(SELECT sab_id FROM sabor where sab_nombre='Manzana'), (SELECT tip_id FROM tipo where tip_nombre='Otro'), 1244),
('Ricura','Chicle', 'Suave',10,'/images/ricura.jpg','Es una bola de caramelo picante con centro de chicle, posee una combinacion particular de sabores.',
(SELECT sab_id FROM sabor where sab_nombre='Piña'), (SELECT tip_id FROM tipo where tip_nombre='Macizo'), 862),
('El Original',NULL ,'Menta Piperita',8,'/images/original.jpg','Caramelo balsamico con el efecto de aliviar la irritacion de garganta y despejar las vias respiratorias; viene en 5 sabores.',
(SELECT sab_id FROM sabor where sab_nombre='Miel y menta'), (SELECT tip_id FROM tipo where tip_nombre='Otro'),1243),
('Dulcin',NULL ,'Blando',7,'/images/5.jpg','Coloridos caramelos blandos masticables de forma cuadrada, vienen en 5 sabores (cada color representa un sabor).',
(SELECT sab_id FROM sabor where sab_nombre='Cereza'), (SELECT tip_id FROM tipo where tip_nombre='Normal'), 2312),
('Choco Candy', 'Cafe con leche','Blandos',5,'/images/4.jpg','Eran pequeñas pastillas de cafe con leche a las que se les atribuian efectos positivos para combatir refriados (actualmente lideres en caramelos en chocolate).',
(SELECT sab_id FROM sabor where sab_nombre='Fresa con nata'), (SELECT tip_id FROM tipo where tip_nombre='Bombon'),1286),
('Blue','Arequipe','Blandos',6,'/images/1.jpg','Caramelo de café elaborado en España al termino de la guerra civil (la receta de CandyUCAB posee un centro de arequipe).',
(SELECT sab_id FROM sabor where sab_nombre='Capuccino'), (SELECT tip_id FROM tipo where tip_nombre='Bombon'),2142);
